name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ] # იმუშავებს როგორც main-ზე, ისე master-ზე

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install # npm ci-ს სანაცვლოდ იყენებს npm install-ს, რაც არ დააფეილებს პროცესს

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # თუ Vite-ს იყენებთ (და არა Create React App-ს), ჩაწერეთ './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4